ci: fix docker tag issue.

diff --git a/.github/workflows/docker-build-publish.yaml b/.github/workflows/docker-build-publish.yaml
--- a/.github/workflows/docker-build-publish.yaml
+++ b/.github/workflows/docker-build-publish.yaml
@@ -24,120 +24,113 @@ jobs:
 
       - name: Set image tags and other variables
         run: |
-          echo ${GITHUB_SHA}
-          echo ${GITHUB_REF}
-          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
           if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
-            echo "Using git tag..."
-            echo "IS_TAG=true" >> $GITHUB_ENV
+            echo "Using git tag ${GITHUB_REF#refs/tags/}..."
             echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
           else
-            echo "Using short commit hash..."
-            echo "IS_TAG=false" >> $GITHUB_ENV
+            echo "Using short commit hash $(echo $GITHUB_SHA | cut -c1-7)..."
+            echo "TAG_NAME=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
           fi
-          echo $IS_TAG
 
-  #     - name: Log in to Docker Hub
-  #       run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+      - name: Log in to Docker Hub
+        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
 
-  #     - name: Install Cosign
-  #       uses: sigstore/cosign-installer@v3.9.2
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@v3.9.2
 
-  #     - name: Build signingService
-  #       working-directory: attestor
-  #       run: |
-  #         docker build \
-  #           -f ./signingService/Dockerfile \
-  #           -t ${{ secrets.DOCKERHUB_USERNAME }}/verulink-attestor-sign:${SHORT_SHA} \
-  #           $( [ "$IS_TAG" = "true" ] && echo "-t ${{ secrets.DOCKERHUB_USERNAME }}/verulink-attestor-sign:${TAG_NAME}" ) \
-  #           .
+      - name: Build signingService
+        working-directory: attestor
+        run: |
+          docker build \
+            -f ./signingService/Dockerfile \
+            -t ${{ secrets.DOCKERHUB_USERNAME }}/verulink-attestor-sign:${TAG_NAME} \
+            .
 
-  #     - name: Push and sign verulink-attestor-sign image
-  #       env:
-  #         COSIGN_YES: "true"
-  #       run: |
-  #         set -e
-  #         IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/verulink-attestor-sign:${SHORT_SHA}
+      - name: Push and sign verulink-attestor-sign image
+        env:
+          COSIGN_YES: "true"
+        run: |
+          set -e
+          IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/verulink-attestor-sign:${TAG_NAME}
 
-  #         echo "Pushing image: $IMAGE"
-  #         docker push $IMAGE
+          echo "Pushing image: $IMAGE"
+          docker push $IMAGE
 
-  #         # Retrieve the digest using docker CLI
-  #         DIGEST=$(docker image inspect $IMAGE --format '{{index .RepoDigests 0}}' | awk -F@ '{print $2}')
+          # Retrieve the digest using docker CLI
+          DIGEST=$(docker image inspect $IMAGE --format '{{index .RepoDigests 0}}' | awk -F@ '{print $2}')
 
-  #         if [ -z "$DIGEST" ]; then
-  #           echo "❌ Digest not found. Image may not have been pushed correctly."
-  #           exit 1
-  #         fi
+          if [ -z "$DIGEST" ]; then
+            echo "❌ Digest not found. Image may not have been pushed correctly."
+            exit 1
+          fi
 
-  #         echo "Digest: $DIGEST"
+          echo "Digest: $DIGEST"
 
-  #         # Sign the image using the digest
-  #         cosign sign "${IMAGE%@*}@${DIGEST}"
+          # Sign the image using the digest
+          cosign sign "${IMAGE%@*}@${DIGEST}"
 
 
 
-  #     - name: Build chainService
-  #       working-directory: attestor
-  #       run: |
-  #         docker build \
-  #           -f ./chainService/Dockerfile \
-  #           -t ${{ secrets.DOCKERHUB_USERNAME }}/verulink-attestor-chain:${SHORT_SHA} \
-  #           $( [ "$IS_TAG" = "true" ] && echo "-t ${{ secrets.DOCKERHUB_USERNAME }}/verulink-attestor-chain:${TAG_NAME}" ) \
-  #           ./chainService
+      - name: Build chainService
+        working-directory: attestor
+        run: |
+          docker build \
+            -f ./chainService/Dockerfile \
+            -t ${{ secrets.DOCKERHUB_USERNAME }}/verulink-attestor-chain:${TAG_NAME} \
+            ./chainService
 
-  #     - name: Push and sign verulink-attestor-chain image
-  #       env:
-  #         COSIGN_YES: "true"
-  #       run: |
-  #         set -e
-  #         IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/verulink-attestor-chain:${SHORT_SHA}
+      - name: Push and sign verulink-attestor-chain image
+        env:
+          COSIGN_YES: "true"
+        run: |
+          set -e
+          IMAGE=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/verulink-attestor-chain:${TAG_NAME}
 
-  #         echo "Pushing image: $IMAGE"
-  #         docker push $IMAGE
+          echo "Pushing image: $IMAGE"
+          docker push $IMAGE
       
-  #         # Retrieve the digest using docker CLI
-  #         DIGEST=$(docker image inspect $IMAGE --format '{{index .RepoDigests 0}}' | awk -F@ '{print $2}')
+          # Retrieve the digest using docker CLI
+          DIGEST=$(docker image inspect $IMAGE --format '{{index .RepoDigests 0}}' | awk -F@ '{print $2}')
       
-  #         if [ -z "$DIGEST" ]; then
-  #           echo "❌ Digest not found. Image may not have been pushed correctly."
-  #           exit 1
-  #         fi
+          if [ -z "$DIGEST" ]; then
+            echo "❌ Digest not found. Image may not have been pushed correctly."
+            exit 1
+          fi
       
-  #         echo "Digest: $DIGEST"
+          echo "Digest: $DIGEST"
       
-  #         # Sign the image using the digest
-  #         cosign sign "${IMAGE%@*}@${DIGEST}"
+          # Sign the image using the digest
+          cosign sign "${IMAGE%@*}@${DIGEST}"
 
-  # verify-sig:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout Repo
-  #       uses: actions/checkout@v4
+  verify-sig:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Repo
+        uses: actions/checkout@v4
 
-  #     - name: Set up Cosign
-  #       uses: sigstore/cosign-installer@v3
+      - name: Set up Cosign
+        uses: sigstore/cosign-installer@v3
 
-  #     - name: Construct and Display cosign verify command
-  #       run: |
-  #         IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
-  #         REPO_NAME="${GITHUB_REPOSITORY#*/}"              # verulink
-  #         REPO_OWNER="${GITHUB_REPOSITORY%/*}"             # venture23-aleo
-  #         BRANCH_REF="${GITHUB_REF}"                       # refs/heads/ci/add-docker-image-build-workflow
-  #         WORKFLOW_FILE=".github/workflows/docker-build-publish.yaml"
+      - name: Construct and Display cosign verify command
+        run: |
+          IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
+          REPO_NAME="${GITHUB_REPOSITORY#*/}"              # verulink
+          REPO_OWNER="${GITHUB_REPOSITORY%/*}"             # venture23-aleo
+          BRANCH_REF="${GITHUB_REF}"                       # refs/heads/ci/add-docker-image-build-workflow
+          WORKFLOW_FILE=".github/workflows/docker-build-publish.yaml"
 
-  #         CERT_IDENTITY="https://github.com/${REPO_OWNER}/${REPO_NAME}/${WORKFLOW_FILE}@${BRANCH_REF}"
+          CERT_IDENTITY="https://github.com/${REPO_OWNER}/${REPO_NAME}/${WORKFLOW_FILE}@${BRANCH_REF}"
 
-  #         echo "🔐 Cosign verify command for Signing service image:"
-  #         echo ""
-  #         echo "cosign verify \\"
-  #         echo "  --certificate-identity \"${CERT_IDENTITY}\" \\"
-  #         echo "  --certificate-oidc-issuer \"https://token.actions.githubusercontent.com\" \\"
-  #         echo "  venture23/verulink-attestor-sign:${IMAGE_TAG}"
+          echo "🔐 Cosign verify command for Signing service image:"
+          echo ""
+          echo "cosign verify \\"
+          echo "  --certificate-identity \"${CERT_IDENTITY}\" \\"
+          echo "  --certificate-oidc-issuer \"https://token.actions.githubusercontent.com\" \\"
+          echo "  venture23/verulink-attestor-sign:${IMAGE_TAG}"
 
-  #         echo "🔐 Cosign verify command for Chain service image:"
-  #         echo ""
-  #         echo "cosign verify \\"
-  #         echo "  --certificate-identity \"${CERT_IDENTITY}\" \\"
-  #         echo "  --certificate-oidc-issuer \"https://token.actions.githubusercontent.com\" \\"
-  #         echo "  venture23/verulink-attestor-chain:${IMAGE_TAG}"
+          echo "🔐 Cosign verify command for Chain service image:"
+          echo ""
+          echo "cosign verify \\"
+          echo "  --certificate-identity \"${CERT_IDENTITY}\" \\"
+          echo "  --certificate-oidc-issuer \"https://token.actions.githubusercontent.com\" \\"
+          echo "  venture23/verulink-attestor-chain:${IMAGE_TAG}"
